context:
  version: "0.0.0"

package:
  name: yuragi
  version: ${{ version }}

source:
  path: ..

build:
  number: 0
  script:
    - mojo precompile src/yuragi -o ${{ PREFIX }}/lib/mojo/yuragi.mojoc

requirements:
  build:
    - mojo-compiler =1.0.0
  host:
    - mojo-compiler =1.0.0
  run:
    - ${{ pin_compatible('mojo-compiler') }}

tests:
  - script:
      - mojo run test_package.mojo
    files:
      recipe:
        - test_package.mojo

about:
  homepage: https://github.com/Ameyanagi/yuragi
  repository: https://github.com/Ameyanagi/yuragi
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
  summary: A CJK-aware fuzzy finder written in Mojo.

extra:
  maintainers:
    - Ameyanagi
